# Generated by Django 3.2.20 on 2023-07-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
    ]
