# Generated by Django 3.2.20 on 2023-07-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
    ]
