# Generated by Django 3.2.20 on 2023-08-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(blank=True, choices=[('CORK', 'CORK'), ('GALWAY', 'GALWAY'), ('DONEGAL', 'DONEGAL'), ('MAYO', 'MAYO'), ('KERRY', 'KERRY'), ('TIPPERARY', 'TIPPERARY'), ('CLARE', 'CLARE'), ('TYRONE', 'TYRONE'), ('ANTRIM', 'ANTRIM'), ('LIMERICK', 'LIMERICK'), ('ROSCOMMON', 'ROSCOMMON'), ('DOWN', 'DOWN'), ('WEXFORD', 'WEXFORD'), ('MEATH', 'MEATH'), ('LONDONDERRY', 'LONDONDERRY'), ('KILKENNY', 'KILKENNY'), ('WICKLOW', 'WICKLOW'), ('OFFALY', 'OFFALY'), ('CAVAN', 'CAVAN'), ('WATERFORD', 'WATERFORD'), ('WESTMEATH', 'WESTMEATH'), ('SLIGO', 'SLIGO'), ('LAOIS', 'LAOIS'), ('KILDARE', 'KILDARE'), ('FERMANAGH', 'FERMANAGH'), ('LEITRIM', 'LEITRIM'), ('ARMAGH', 'ARMAGH'), ('MONOGHAN', 'MONOGHAN'), ('LONGFORD', 'LONGFORD'), ('DUBLIN', 'DUBLIN'), ('CARLOW', 'CARLOW'), ('LOUTH', 'LOUTH')], max_length=30, null=True),
        ),
    ]
