# Generated by Django 3.2.20 on 2023-08-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Vip', 'Vip'), ('Basic', 'Basic')], default='FALSE', max_length=5),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
