# Generated by Django 3.2.20 on 2023-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20230814_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(True, True), (False, False)], default=True, max_length=5),
        ),
    ]
