# Generated by Django 3.2.20 on 2023-08-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20230825_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
