# Generated by Django 3.2.20 on 2023-08-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20230825_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
